### ISSUE TITLE
List all IPs in a range

### ISSUE THREAD

**Issue by jreyes4949** [briansworth/GetIPv4Address#1]
Not an issue but a general question. How can I list out all IPs in a given cidr range? I see in the examples this function can give first and last but any suggestions on how to get everything in between? I want to run some PS to test each host.

**Comment by briansworth** [comment]
One of the helper functions I made accessible in the module makes this pretty easy - `Add-IntToIPv4Address`.
The easiest implementation uses a for loop:
```powershell
$subnet = Get-IPv4Subnet -IPAddress '10.0.0.0' -PrefixLength 23

$subnetRange = New-Object -TypeName Collections.Generic.List[string]
for ($i = 0; $i -lt $subnet.HostCount; $i++)
{
  $ip = Add-IntToIPv4Address -IPv4Address $subnet.FirstHostIP -Integer $i
  $subnetRange.Add($ip)
}
```

The variable $subnetRange should now have all IP Addresses in the 10.0.0.0/23 range.
